- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: ansible/go.yml
    - include_tasks: ansible/zsh.yml
    - include_tasks: ansible/npm.yml
    - include_tasks: ansible/nvim.yml
    - include_tasks: ansible/tmux.yml
    - include_tasks: ansible/ranger.yml
    - include_tasks: ansible/pwsh.yml
    - include_tasks: ansible/kubectl.yml
