- name: install-dependencies
  apt:
    name: ["libc++-dev", "tar"]
- name: download zip
  shell: wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
- name: remove old installations
  shell: rm -rf /usr/local/go
- name: extract zip
  shell: tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
- name: remove zip
  shell: rm go1.21.6.linux-amd64.tar.gz

