- name: install nvim dependencies
  apt:
    name: [ "ripgrep", "gcc", "make", "unzip", "fd-find", "fzf", "cmake", "libfuse2", "cargo" ]
  tags:
    - nvim
    - install
- name: create .config if it doesn't exist
  shell: mkdir -p "${HOME}/.config"
  tags:
    - nvim
    - install
- name: link nvim config
  shell: ln -s "$(pwd)/nvim" "${HOME}/.config/nvim"
  tags:
    - nvim
    - install
- name: download neovim
  shell: curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
  # shell: curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
- name: make neovim executable
  shell: chmod u+x nvim.appimage
- name: add to path
  shell: mv nvim.appimage /usr/local/bin/nvim
