- name: clone tmux plugin repo
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
- name: install tmux
  apt:
    name: tmux
- name: make config dir
  shell: mkdir -p ~/.config/tmux
- name: link tmux conf
  shell: ln -s "$(pwd)/tmux/tmux.conf" "${HOME}/.config/tmux/tmux.conf"

- name: install dependencies
  apt:
    name: [ "cargo", "fzf" ]
- name: install zoxide
  shell: cargo install zoxide
