name: "Credly Badges"

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@2.4.0
