name: "Credly Badges"

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  credly-badges:
    name: "Update README with Credly badges"
    runs-on: ubuntu-latest

    steps:
      - name: Update
        uses: mikejoh/credly-badges@0.4.1
        with:
          CREDLY_USERNAME: nachoxmacho
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update Credly badges!"
